spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/vv
    username: postgres
    password: qqq
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: db/changelog.xml
    enabled: true